### ISSUE TITLE
Could these also include left- and right-sections?

### ISSUE THREAD

**Issue by CrossEye** [rbuckton/proposal-functional-operators#1]
I don't know enough about the parsing to know if this is possible, but it would be really nice if this would also allow for left- and right-[sections][se]:

  * `{2 **}` (left section) is equivalent to  `x => 2 ** x`
  * `{** 2}` (right section) is equivalent to  `x => x ** 2`

Obviously there is a problem with unary negation, and I don't know if that can be overcome, but this would be really convenient.

  [se]: https://wiki.haskell.org/Section_of_an_infix_operator

**Comment by masaeedu** [comment]
@CrossEye Is this just sugar for `2 {**}` and `{**} 2`? Maybe I'm misunderstanding you.

**Comment by CrossEye** [comment]
Sorry, I somehow entirely missed the [fixed arguments][fa] section.; I have no idea how.  That is exactly what I was looking for.  Sorry for the confusion.


  [fa]: https://github.com/rbuckton/proposal-functional-operators#fixed-arguments
